Kubernetes gitops
otus-kuber-2020-07/vasiliev-alexey_platform pull request #11
Opened 2020-10-07 18:22 UTC by vasiliev-alexey

# Выполнено ДЗ № 10 "GitOps и инструменты поставки"

 - [ ] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
## Создали [проект в GitLab](https://gitlab.com/vasiliev-alexey/microservices-demo) и залили в него исходные коды 

* создали чарты для развертывания
* пришлось немного подрисовать в процессе - на фронте удалил деплоймент мониторинга
* [автоматизировали создание](https://gitlab.com/vasiliev-alexey/gke-tf-cluster) кластера k8s через Terraform
* Создали [Makefile](https://gitlab.com/vasiliev-alexey/microservices-demo/-/blob/master/src/Makefile) для ручной сборки и пуша образов микросервисов
* Запилили [пайплайн](https://gitlab.com/vasiliev-alexey/microservices-demo/-/blob/master/.gitlab-ci.yml) сборки микросервисов

## GitOps

* автоматизировано [развертывание fluxcd и fluxcd/helm-operator через Terraform](gitops/main.tf)
* Созданы [манифесты для развертывания HelmRelease](https://gitlab.com/vasiliev-alexey/microservices-demo/-/tree/master/deploy/releases) для всех микросервисов
Проверка измнений осуществляется через обсчет Хеша в конфигурационных файлах, по ключевым полям

~~~ sh
ts=2020-10-02T19:23:17.650372165Z caller=daemon.go:701 component=daemon event="Sync: 1190d12, microservices-demo:helmrelease/frontend-hipster" logupstream=false

~~~

~~~ sh
  Last Attempted Revision:  47bc110a79f3a2b42d55446c2a4209ee3379686a
  Observed Generation:      2
  Phase:                    Succeeded
  Release Name:             frontend
  Release Status:           deployed
  Revision:                 47bc110a79f3a2b42d55446c2a4209ee3379686a
~~~

## Canary deployments с Flagger и IstioFlagger и Istio

* Установку Istio  - пропустили, реализовывается через GKE

~~~ yaml
 addons_config {
    istio_config {
      disabled = false
      auth     = "AUTH_NONE"
    }
  }
~~~

* Автоматизирована установка Flagger  с помощью [Terraform](flagger/main.tf)  
  Для установки CRD   применен новый провайдер для [k8s-terraform](https://github.com/hashicorp/terraform-provider-kubernetes-alpha). Для корректной работы требуется k8s версии не ниже 1.17 - поднял версию в инфраструктурном проекте
* Дали доступ для микросервиса  frontend
* Создали манифест для Canary-развертывания
* Определите причину неуспешности релиза - причина в  том, что flagger не получает метрик от Prometheus сервера.
* Добейтесь успешного выполнения релиза - не получилось, (то ли  тупой, то ли лыжи не едут. Почитал исходники, инциденты на GH  - не разобрался)

~~~ sh
kubectl get canaries --all-namespaces                                                                                                                                                                                                    21:00:01 07/10/20
NAMESPACE            NAME       STATUS   WEIGHT   LASTTRANSITIONTIME
microservices-demo   frontend   Failed   0        2020-10-07T17:29:23Z
~~~

~~~ json
"level":"info","ts":"2020-10-07T17:28:23.014Z","caller":"controller/events.go:28","msg":"Halt advancement no values found for istio metric request-success-rate probably frontend.microservices-demo is not receiving traffic: running query failed: no values found","canary":"frontend.microservices-demo"}

~~~

## Как запустить проект:
 Поднимаем инфраструктуру GKE

~~~ sh
export TF_VAR_project_name=XXX
cd kubernetes-gitops/infra && terraform apply -auto-approve
~~~

Деплоим инфраструктуру для gitops
~~~ sh
export TF_VAR_project_name=XXX
cd kubernetes-gitops/gitops && terraform apply -auto-approve
~~~

Деплоим инфраструктуру для Flagger
~~~ sh
export TF_VAR_project_name=XXX
cd kubernetes-gitops/flagger && terraform apply -auto-approve
~~~

## Как проверить работоспособность:
 - не придумал

## PR checklist:
 - [x] Выставлен label с темой домашнего задания

2020-10-12 08:19 UTC, Jasstkn requested changes
Добрый день. Поревьюила дз, оставила комментарий по поводу проблем с кенери

2020-10-12 08:19 UTC, Jasstkn commented on kubernetes-gitops/README.md
> +* [автоматизировали создание](https://gitlab.com/vasiliev-alexey/gke-tf-cluster) кластера k8s через Terraform
терраформ не умеет управлять бакетом, который использует для хранения стейта - нужно руками его создавать всегда.

2020-10-12 08:19 UTC, Jasstkn commented on kubernetes-gitops/README.md
> +* Запилили [пайплайн](https://gitlab.com/vasiliev-alexey/microservices-demo/-/blob/master/.gitlab-ci.yml) сборки микросервисов
Здорово, что попрактиковались с инклюдами пайплайнов и темплейтами.

2020-10-12 08:19 UTC, Jasstkn commented on kubernetes-gitops/README.md
> +"level":"info","ts":"2020-10-07T17:28:23.014Z","caller":"controller/events.go:28","msg":"Halt advancement no values found for istio metric request-success-rate probably frontend.microservices-demo is
а эта метрика есть? попробуйте заменить на другую.

2020-10-12 10:20 UTC, vasiliev-alexey commented on kubernetes-gitops/README.md
> +* [автоматизировали создание](https://gitlab.com/vasiliev-alexey/gke-tf-cluster) кластера k8s через Terraform
Бакет рабочий, что-то с правами на запись в него для  созданного сервисного  аккаунта в IAM - видимо надо каких-то грантов никидать.

2020-10-12 16:17 UTC, vasiliev-alexey commented on kubernetes-gitops/README.md
> +"level":"info","ts":"2020-10-07T17:28:23.014Z","caller":"controller/events.go:28","msg":"Halt advancement no values found for istio metric request-success-rate probably frontend.microservices-demo is
Разобрался, действительно не прокатил манифесты [создающие CRD](https://storage.googleapis.com/gke-release/istio/release/1.0.6-gke.3/patches/install-prometheus.yaml) для Prometheus .
Не удалось их конвертировать в манифеесты Terraform (инструмент еще не может их конвертнуть) -  пришлось приложить так.

2020-10-16 06:39 UTC, Jasstkn approved these changes
Принимаю домашку 👍

2020-10-16 06:40 UTC, merged